/********************************************************************
* src/Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDict();
extern void G__cpp_setup_inheritanceDict();
extern void G__cpp_setup_typetableDict();
extern void G__cpp_setup_memvarDict();
extern void G__cpp_setup_globalDict();
extern void G__cpp_setup_memfuncDict();
extern void G__cpp_setup_funcDict();
extern void G__set_cpp_environmentDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/patrick/SiPM_MC/include/HitMatrix.hh"
#include "/home/patrick/SiPM_MC/include/PhotonList.hh"
#include "/home/patrick/SiPM_MC/include/PhotonSource.hh"
#include "/home/patrick/SiPM_MC/include/sipmMC.hh"
#include "/home/patrick/SiPM_MC/include/daqMC.hh"
#include "/home/patrick/SiPM_MC/include/sipmGUI.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__DictLN_string;
extern G__linked_taginfo G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_TList;
extern G__linked_taginfo G__DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DictLN_TF1;
extern G__linked_taginfo G__DictLN_TH1D;
extern G__linked_taginfo G__DictLN_TH1;
extern G__linked_taginfo G__DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DictLN_TH2;
extern G__linked_taginfo G__DictLN_TH2I;
extern G__linked_taginfo G__DictLN_TH2D;
extern G__linked_taginfo G__DictLN_TQObjSender;
extern G__linked_taginfo G__DictLN_TCanvas;
extern G__linked_taginfo G__DictLN_TPad;
extern G__linked_taginfo G__DictLN_HitMatrix;
extern G__linked_taginfo G__DictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_PhotonList;
extern G__linked_taginfo G__DictLN_TRandom3;
extern G__linked_taginfo G__DictLN_PhotonSource;
extern G__linked_taginfo G__DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DictLN_TGraphErrors;
extern G__linked_taginfo G__DictLN_GCharge;
extern G__linked_taginfo G__DictLN_sipmMC;
extern G__linked_taginfo G__DictLN_GResonseCurve;
extern G__linked_taginfo G__DictLN_daqMC;
extern G__linked_taginfo G__DictLN_TGCompositeFrame;
extern G__linked_taginfo G__DictLN_TGLayoutHints;
extern G__linked_taginfo G__DictLN_TGTextButton;
extern G__linked_taginfo G__DictLN_TGGroupFrame;
extern G__linked_taginfo G__DictLN_TGButtonGroup;
extern G__linked_taginfo G__DictLN_TGCheckButton;
extern G__linked_taginfo G__DictLN_TGNumberEntry;
extern G__linked_taginfo G__DictLN_TGLabel;
extern G__linked_taginfo G__DictLN_TGComboBox;
extern G__linked_taginfo G__DictLN_TGHProgressBar;
extern G__linked_taginfo G__DictLN_sipmGUI;

/* STUB derived class for protected member access */
